//! Defines external events entering the TUI event loop.

/// External events that the TUI must process.
///
/// These are typically generated by the terminal backend (crossterm) or
/// internal timers, abstracting the raw input into a domain-specific enum.
#[derive(Debug, Clone)]
pub enum Event {
    /// A keyboard event.
    Key(crossterm::event::KeyEvent),
    /// A terminal resize event with new columns and rows.
    Resize(u16, u16),
    /// A periodic tick for UI updates (e.g., progress bars, clocks).
    Tick,
    /// A custom application-defined event.
    Custom(String),
}
